{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cloudian-exporter.fullname" . }}
  labels:
    {{- include "cloudian-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
      {{- include "cloudian-exporter.labels" . | nindent 14 }}
{{- end -}}